# Generated by Django 5.2.6 on 2025-10-13 20:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(fields=('author', 'post'), name='unique_post_reaction_author'),
        ),
    ]
