# Generated by Django 5.2.6 on 2025-10-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_reaction_unique_post_reaction_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='geo_data',
            field=models.JSONField(null=True),
        ),
    ]
